version: 2.1

jobs:
  build:
    docker:
      - image: cimg/node:22.0.0

    working_directory: ~/website

    steps: 
      - checkout

      - run:
          name: install Dependencies
          command: npm install

      - run:
          name: Build
          command: npm run build

  deploy:
    docker:
      - image: cimg/python:3.8.4

    working_directory: ~/website

    steps:
      - checkout

      - run:
          name: Deploy to GitHub Pages
          command: |
            git config --global user.email "fierceblizzard11@gmail.com"
            git config --global user.name "fierceblizzard"
            git checkout main
            cp -r dist/* .
            git add .
            git commit -m "Deploying to GitHub Pages"
            git push origin main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: main